version: "3.8"
services:
  gateway:
    build: ./gateway
    env_file: ./gateway/.env
    ports:
      - 3000:3000
    environment:
      - READ_GRPC_URL=host-grpc-t:5200
      - WRITE_GRPC_URL=host-grpc-t:5100
    restart: unless-stopped

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ~/.docker-data/mongodb:/data/db
    logging:
      driver: none

  read-service:
    build: ./read-service
    env_file: ./read-service/.env
    hostname: host-grpc-t
    ports:
      - 3200:3200
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/test-grpc
      - GRPC_URL=host-grpc-t:5200
    restart: on-failure
    depends_on:
      - mongodb

  write-service:
    build: ./write-service
    env_file: ./write-service/.env
    hostname: host-grpc-t
    ports:
      - 3100:3100
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/test-grpc
      - GRPC_URL=host-grpc-t:5100
    restart: on-failure
    depends_on:
      - mongodb
